"""
Candidate pipeline data for Moolchand Healthcare Group.
Update candidate statuses, notes, and actions here.
"""

POSITIONS = {
    "FIN-001": "Sr Finance Manager / Finance & AR Lead",
    "RPA-001": "RPA Developer",
    "DRO-001": "Chief Digital Revenue Officer",
}

# Statuses: HIRED, PRIMARY, BACKUP, OPTIONAL, ON_HOLD, EXCLUDED, REJECTED, WITHDRAWN, BACKED_OUT
CANDIDATES = [
    # ── Finance (FIN-001) ──────────────────────────────────────────────
    {
        "id": "FIN-JAT-001",
        "name": "Jatin Sachdeva",
        "position": "FIN-001",
        "status": "HIRED",
        "score": 7.2,
        "ctc": "₹4.5L",
        "notice_days": 0,
        "joining_date": "2026-06-18",
        "source": "GIST Consulting",
        "contact": "",
        "phone": "",
        "notes": "4 yrs general accounting. Onboarding prep in progress.",
        "action": "Confirm onboarding details and first-day logistics.",
    },
    {
        "id": "FIN-RAH-001",
        "name": "CA Rahul Madaan",
        "position": "FIN-001",
        "status": "PRIMARY",
        "score": 8.8,
        "ctc": "₹42-44L (offer)",
        "notice_days": 30,
        "joining_date": "2026-06-15",
        "source": "GIST Consulting",
        "contact": "rahulmadaan942@gmail.com",
        "phone": "9873060422",
        "notes": "8 yrs (ECSO Global, CarDekho, BDO, Mazars). CA, C2C & AR expert. No red flags.",
        "action": "CONTACT TODAY — only viable Finance option after Abhishek declined, Vikas rejected.",
    },
    {
        "id": "FIN-MAN-001",
        "name": "CA Manu Singla",
        "position": "FIN-001",
        "status": "BACKUP",
        "score": 8.9,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Too junior — only 3 years experience.",
        "action": "Activate if Rahul unavailable.",
    },
    {
        "id": "FIN-JAT-002",
        "name": "CA Jatin Anand",
        "position": "FIN-001",
        "status": "BACKUP",
        "score": 8.5,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "6 years experience.",
        "action": "Activate if Rahul unavailable.",
    },
    {
        "id": "FIN-KAP-001",
        "name": "CA Kapil Sharma",
        "position": "FIN-001",
        "status": "BACKUP",
        "score": 7.8,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "7 years experience.",
        "action": "Activate if Rahul unavailable.",
    },
    {
        "id": "FIN-RIT-001",
        "name": "Ritu Arora",
        "position": "FIN-001",
        "status": "BACKUP",
        "score": 8.2,
        "ctc": "₹31.67L (current)",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "7 years experience. High CTC expectation.",
        "action": "Activate if Rahul unavailable.",
    },
    {
        "id": "FIN-SHU-001",
        "name": "Shukla Satia",
        "position": "FIN-001",
        "status": "BACKUP",
        "score": 7.8,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "6 years experience.",
        "action": "Activate if Rahul unavailable.",
    },
    {
        "id": "FIN-ABH-001",
        "name": "CA Abhishek Goyal",
        "position": "FIN-001",
        "status": "REJECTED",
        "score": 9.3,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Declined offer despite highest score.",
        "action": "",
    },
    {
        "id": "FIN-VIK-001",
        "name": "Vikas Jain",
        "position": "FIN-001",
        "status": "REJECTED",
        "score": 7.5,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Rejected by Moolchand — SAP gap, weak AR/C2C.",
        "action": "",
    },
    # ── RPA (RPA-001) ─────────────────────────────────────────────────
    {
        "id": "RPA-RIT-001",
        "name": "Ritik Gupta",
        "position": "RPA-001",
        "status": "BACKED_OUT",
        "score": 8.8,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Was confirmed hired; withdrew offer after acceptance.",
        "action": "",
    },
    {
        "id": "RPA-KAM-001",
        "name": "Kamal",
        "position": "RPA-001",
        "status": "PRIMARY",
        "score": 7.8,
        "ctc": "₹6.6L",
        "notice_days": 90,
        "joining_date": "2026-07-01",
        "source": "GIST Consulting — Hemant Kulasri",
        "contact": "",
        "phone": "",
        "notes": "UiPath Orchestrator expert. Negotiate notice to 60 days.",
        "action": "CONTACT THIS WEEK via GIST — offer ₹6.6L.",
    },
    {
        "id": "RPA-ANS-001",
        "name": "Anshul Vashisth",
        "position": "RPA-001",
        "status": "PRIMARY",
        "score": 8.8,
        "ctc": "₹6L + ₹2-3L SAP training",
        "notice_days": 0,
        "joining_date": "2026-07-01",
        "source": "Internal",
        "contact": "",
        "phone": "",
        "notes": "SAP FICO integration — critical for HANA. Immediate joiner.",
        "action": "CONTACT WEEK 2 — offer ₹6L + approve SAP training budget.",
    },
    {
        "id": "RPA-SHA-001",
        "name": "Shahe Faisal",
        "position": "RPA-001",
        "status": "OPTIONAL",
        "score": 8.5,
        "ctc": "₹13-15L (market rate)",
        "notice_days": 15,
        "joining_date": "",
        "source": "PDF (May 18)",
        "contact": "",
        "phone": "",
        "notes": "Capgemini Rising Star. Competing: Cognizant ₹13L, TCS ₹13L.",
        "action": "Consider only if premium budget (₹15L) approved.",
    },
    {
        "id": "RPA-SUB-001",
        "name": "Subrat",
        "position": "RPA-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Limited enterprise experience.",
        "action": "",
    },
    {
        "id": "RPA-JAS-001",
        "name": "Jasmin Bar",
        "position": "RPA-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Limited enterprise experience.",
        "action": "",
    },
    {
        "id": "RPA-HAR-001",
        "name": "Hardik Agarwal",
        "position": "RPA-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Junior — mentorship-pair only.",
        "action": "",
    },
    # ── DRO (DRO-001) ─────────────────────────────────────────────────
    {
        "id": "DRO-KUW-001",
        "name": "Kuwarjeet Sidana",
        "position": "DRO-001",
        "status": "PRIMARY",
        "score": 9.5,
        "ctc": "₹28L (offer)",
        "notice_days": 30,
        "joining_date": "2026-06-15",
        "source": "GIST Consulting",
        "contact": "kuwarjeetsingh18@gmail.com",
        "phone": "8800100021",
        "notes": "10 yrs total; 3.5 yrs Fortis Healthcare. 130+ Cr digital revenue. NO backup.",
        "action": "INTERVIEW THIS WEEK — CRITICAL, no backup available. Offer ₹28L.",
    },
    # ── On Hold ────────────────────────────────────────────────────────
    {
        "id": "OH-RAJ-001",
        "name": "Rajeev Rana",
        "position": "FIN-001",
        "status": "ON_HOLD",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "",
        "action": "Re-evaluate if primary and backups fall through.",
    },
    {
        "id": "OH-BHA-001",
        "name": "CA Bharat Singh",
        "position": "FIN-001",
        "status": "ON_HOLD",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "",
        "action": "Re-evaluate if primary and backups fall through.",
    },
    # ── Excluded / Withdrawn ──────────────────────────────────────────
    {
        "id": "EX-BHS-001",
        "name": "CA Bharat Sharma",
        "position": "FIN-001",
        "status": "EXCLUDED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Exceeds 6-10yr ceiling.",
        "action": "",
    },
    {
        "id": "EX-ABJ-001",
        "name": "CA Abhinav Jain",
        "position": "FIN-001",
        "status": "EXCLUDED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Exceeds 6-10yr ceiling.",
        "action": "",
    },
    {
        "id": "WD-SHJ-001",
        "name": "Shivani Jain",
        "position": "FIN-001",
        "status": "WITHDRAWN",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "Candidate withdrew.",
        "action": "",
    },
    # ── Additional rejected (Finance) ─────────────────────────────────
    {
        "id": "FIN-HAR-001",
        "name": "Harit Kumar",
        "position": "FIN-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "",
        "action": "",
    },
    {
        "id": "FIN-UPA-001",
        "name": "Upasana Gautam",
        "position": "FIN-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "",
        "action": "",
    },
    {
        "id": "FIN-PRA-001",
        "name": "Pragati Kumari",
        "position": "FIN-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "",
        "action": "",
    },
    {
        "id": "FIN-VMR-001",
        "name": "V. Mohan Reddy",
        "position": "FIN-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "",
        "action": "",
    },
    {
        "id": "FIN-SSA-001",
        "name": "Shyam Sagar",
        "position": "FIN-001",
        "status": "REJECTED",
        "score": 0,
        "ctc": "",
        "notice_days": None,
        "joining_date": "",
        "source": "",
        "contact": "",
        "phone": "",
        "notes": "",
        "action": "",
    },
]

STATUS_LABELS = {
    "HIRED": "Hired",
    "PRIMARY": "Primary",
    "BACKUP": "Backup",
    "OPTIONAL": "Optional",
    "ON_HOLD": "On Hold",
    "EXCLUDED": "Excluded",
    "REJECTED": "Rejected",
    "WITHDRAWN": "Withdrawn",
    "BACKED_OUT": "Backed Out",
}

ACTIVE_STATUSES = {"HIRED", "PRIMARY", "BACKUP", "OPTIONAL", "ON_HOLD"}
